"""add_contract_metadata_fields

Revision ID: fb5aed732e02
Revises: 11a8299a43ee
Create Date: 2025-05-06 14:26:18.371299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5aed732e02'
down_revision: Union[str, None] = '11a8299a43ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options_contracts', sa.Column('cfi_code', sa.String(), nullable=True))
    op.add_column('options_contracts', sa.Column('exercise_style', sa.String(), nullable=True))
    op.add_column('options_contracts', sa.Column('primary_exchange', sa.String(), nullable=True))
    op.add_column('options_contracts', sa.Column('shares_per_contract', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options_contracts', 'shares_per_contract')
    op.drop_column('options_contracts', 'primary_exchange')
    op.drop_column('options_contracts', 'exercise_style')
    op.drop_column('options_contracts', 'cfi_code')
    # ### end Alembic commands ###
